### ISSUE TITLE
Email addresses are not being added to PostUp lists

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/mailer#10]
Testing the NGPS modules and none of the test addresses are making it on to the lists for any of the six widgets created, which points to a mailer problem.

Not sure if it's related, but when I test the forms on an article, the javascript writes the thank you message as expected, but when testing in Dash, I'm redirected to the Sports splash landing page that I built for the SPORTS (2015) list.

@freejoe76 Can you see if anything is obviously wrong in the script before we start brainstorming solutions?

**Comment by schneidan** [comment]
Eric, didn't PostUp have to whitelist the IP of the server for the original boxes to work? Did the app move to a different server?

**Comment by freejoe76** [comment]
@schneidan it didn't move to a new server, no.

**Comment by schneidan** [comment]
Okay, that was the first easy fix I could think of.

Eric, are these new lists? Did we check the box? ;-)

**Comment by ericjlubbers** [comment]
@schneidan First thing I checked. They are all very much open to public signup (which was the box in question).

**Comment by schneidan** [comment]
Okay. Going back to my regularly scheduled day off, then. Good luck!

**Comment by freejoe76** [comment]
This is fixed.
