### ISSUE TITLE
Unexplained slowness

### ISSUE THREAD

**Issue by schneidan** [denverpost/mailer#12]
The denverpostplus.com/mailer-rules/ implementation of the repo is working, but taking 90-120 seconds to return successfully according to Eric's testing on the new Cannabist signup page.

I took a look at the php and apache error logs on the server and didn't see anything.

@ericjlubbers: Can you maybe set up a test copy of that page that uses the mailer-rules form method so @freejoe76 can take a look?

**Comment by freejoe76** [comment]
@ericjlubbers no need to set up a test copy of the page, I can test this locally.

**Comment by ericjlubbers** [comment]
Good @freejoe76, because I hadn't done it yet.

**Comment by freejoe76** [comment]
This is fixed -- in an effort to see if sign-ups were being missed I added a mail() call to the script. The mail() call slowed down the script a ton.

**Comment by freejoe76** [comment]
Update: I fixed the slowness in the mail function, thanks to this article: http://www.alphadevx.com/a/372-Fixing-slow-performance-of-sending-mail-from-PHP-via-Sendmail
