### ISSUE TITLE
Create Wordpress-friendly signup widget

### ISSUE THREAD

**Issue by ericjlubbers** [denverpost/mailer#14]
Improve styling of this widget (http://extras.denverpost.com/app/mailer-rules/roundup-widget.html) for use on Wordpress and streamline the "thank you" confirmation page.

Head-in-the-clouds feature request: make the iframe URL include a variable (*tech*, *roundup*, *broncos* etc.) that will load different language and configure the form to add an email to a different list.

If that can be done, then adding an "Insert newsletter signup widget" option to AUTO 🤖 PRODUCER would be easier, I'd imagine.

**Comment by danielpetty** [comment]
Adding that I think, stylistically, this is clean and minimalist. A good model (mid-way through the story):

http://digiday.com/media/notoriously-difficult-inside-unraveling-thrillist-jackthreads-marriage-content-commerce/
