### ISSUE TITLE
This should work for at least three newsletters, and should be easy to add more if we want.

### ISSUE THREAD

**Issue by freejoe76** [denverpost/mailer#6]
@ericjlubbers how are these newsletters defined and how should they communicated in the GET/POST request? "&newsletter_id=breaking"?

**Comment by freejoe76** [comment]
The LIST_CODE variable will be the alpha ID I get back from PostUp on the three new lists I've created. I just filed the ticket. When I get them, I'll add them to this document under the 2015 Newsletter Push heading: https://docs.google.com/spreadsheets/d/1TSCDQMOhUYkzyJPNAjkFg9yjUoCO0MAm1m55UHVcZ5I/edit#gid=0 (edited)

**Comment by ericjlubbers** [comment]
@freejoe76: The alpha IDs for the lists we're using have been added to the spreadsheet: https://docs.google.com/spreadsheets/d/1TSCDQMOhUYkzyJPNAjkFg9yjUoCO0MAm1m55UHVcZ5I/edit#gid=0

**Comment by freejoe76** [comment]
@ericjlubbers Thanks. Almost ready to launch one of these. Is that NUMERIC_CODE field used for anything?

**Comment by ericjlubbers** [comment]
Nope. It's just the only ID we can get directly out of PostUp. We have to
file a ticket to get the alpha version of that ID.

_Eric J. Lubbers_
Mobile Editor - The Denver Post
elubbers@denverpost.com / 303-954-2615 / @ericjlubbers
http://twitter.com/ericjlubbers

**Comment by freejoe76** [comment]
Done.
